package com.dental.model;

/**
 * Represents a Patient in the Dental Clinic Management System.
 * Maps to the 'patients' table in the database.
 */
public class Patient {

    // Primary Key - auto-generated by DB
    private int id;

    // Optional foreign key to users table (if patients are linked to user accounts)
    private Integer userId;

    // Personal & Contact Info
    private String nic;           // National Identity Card number
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String address;

    // Medical Info
    private String dob;           // Date of Birth - stored as "yyyy-MM-dd" for HTML date input
    private String gender;        // e.g., "Male", "Female", "Other"
    private String medicalHistory; // Allergies, conditions, medications, etc.

    // ==============================
    // Constructors
    // ==============================

    /**
     * Default constructor for frameworks (JPA, Servlets, etc.)
     */
    public Patient() {}

    /**
     * Full constructor for creating a Patient with all fields.
     *
     * @param id              Primary key (auto-generated, use 0 for new patients)
     * @param userId          Optional user ID (if linked to user account)
     * @param nic             National ID
     * @param firstName       First name
     * @param lastName        Last name
     * @param email           Email address
     * @param phone           Phone number
     * @param address         Physical address
     * @param dob             Date of birth (format: "yyyy-MM-dd")
     * @param gender          Gender
     * @param medicalHistory  Medical history notes
     */
    public Patient(int id, Integer userId, String nic, String firstName, String lastName,
                   String email, String phone, String address, String dob, String gender,
                   String medicalHistory) {
        this.id = id;
        this.userId = userId;
        this.nic = nic;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.dob = dob;
        this.gender = gender;
        this.medicalHistory = medicalHistory;
    }

    // ==============================
    // Getters & Setters
    // ==============================

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getNic() {
        return nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDob() {
        return dob;
    }

    public void setDateOfBirth(String dob) {
        this.dob = dob;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getMedicalHistory() {
        return medicalHistory;
    }

    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory;
    }

    // ==============================
    // Optional: toString() for debugging
    // ==============================

    @Override
    public String toString() {
        return "Patient{" +
                "id=" + id +
                ", userId=" + userId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}